#!/bin/bash

# Get the list of active VPN connections
vpn_connections=$(nmcli connection show | grep vpn | awk '{print $1}')
primary_connection=$(nmcli connection show --active | grep wifi | awk '{print $1}')

if [ -z "$vpn_connections" ]; then
	echo "No VPN connections found."
else
	echo "Select a VPN connection:"
		select vpn_connection in ${vpn_connections[@]} "Disconnect" "Import Server"; do
			if [  "$vpn_connection" == "Disconnect" ]; then
				echo "Disconnecting from VPN..."
				nmcli connection modify id $primary_connection ipv6.method auto && nmcli connection up id $primary_connection
			elif [ "$vpn_connection" == "Import Server" ]; then
				read -p "Enter Full Path Of .ovpn File You Want To Import: " fileLocation
					echo "Adding VPN Server To System..."
					echo "$fileLocation"
					nmcli connection import type openvpn file  "$fileLocation"
							fileName=$(basename $fileLocation) && vpnName=$(echo "$fileName" | sed 's/.ovpn//') 	# Removes .ovpn from file name
				read -p "Enter username for VPN: " username
				read -sp "Enter password for VPN: " password
					nmcli connection modify "${vpnName}" +vpn.data username="${username}" && nmcli connection modify "${vpnName}" +vpn.secrets password="${password}"
					echo "......."
					echo "Username and Password added to server..."
					echo "Server added to list of connections"
			elif [ -n "$vpn_connection" ]; then
       				echo "Connecting to: $vpn_connection..."
       				nmcli connection modify id $primary_connection ipv6.method disabled && nmcli connection up id $primary_connection && nmcli connection up $vpn_connection
        fi
        break
    done
fi
